# Generated by Django 4.1.7 on 2023-03-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Renk'),
        ),
    ]
