# Generated by Django 4.1.7 on 2023-03-06 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(verbose_name='Oluşturulma Tarihi')),
                ('updated_date', models.DateTimeField(verbose_name='Düzenlenme Tarihi')),
                ('start_date', models.DateTimeField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateTimeField(verbose_name='Bitiş Tarihi')),
                ('patient_name', models.CharField(max_length=30, verbose_name='Hasta Adı')),
                ('patient_surname', models.CharField(max_length=30, verbose_name='Hasta Soyadı')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Randevu',
                'verbose_name_plural': 'Randevular',
                'db_table': 'appointments',
            },
        ),
    ]
