# Generated by Django 4.1.7 on 2023-03-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Düzenlenme Tarihi'),
        ),
    ]
